import { Event, BlogPost, EntityPartner, ServiceItem, Testimonial, TeamMember, GalleryItem, VideoItem, EventRegistration, Enquiry } from '@/types';

export const mockPartners: EntityPartner[] = [
  // Sponsors
  {
    id: 'sp-1',
    category: 'sponsor',
    name: 'Apex Global Financial Services',
    logoUrl: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&w=300&q=80',
    websiteUrl: 'https://example.com',
    description: 'Title Platinum Sponsor powering enterprise MSME loan distribution at MCU expos.',
    tier: 'platinum',
    displayOrder: 1,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'sp-2',
    category: 'sponsor',
    name: 'Vanguard Tech Infra',
    logoUrl: 'https://images.unsplash.com/photo-1516876437184-593fda40c7ce?auto=format&fit=crop&w=300&q=80',
    websiteUrl: 'https://example.com',
    description: 'Official Gold Sponsor providing cloud POS infrastructure and high-speed venue mesh networks.',
    tier: 'gold',
    displayOrder: 2,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'sp-3',
    category: 'sponsor',
    name: 'Kovai Fresh Beverages',
    logoUrl: 'https://images.unsplash.com/photo-1551836022-deb4988cc6c0?auto=format&fit=crop&w=300&q=80',
    websiteUrl: 'https://example.com',
    description: 'Official Beverage Partner offering refreshments across VIP lounges and exhibitor stalls.',
    tier: 'silver',
    displayOrder: 3,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'sp-4',
    category: 'sponsor',
    name: 'The Hindu Businessline',
    logoUrl: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=300&q=80',
    websiteUrl: 'https://example.com',
    description: 'Official Print & Digital Media Partner delivering statewide event coverage.',
    tier: 'media',
    displayOrder: 4,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },

  // Strategic Partners
  {
    id: 'pt-1',
    category: 'partner',
    name: 'CODISSIA Trade Center',
    logoUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=300&q=80',
    websiteUrl: 'https://example.com',
    description: 'Official Venue Partner hosting premier exhibitions and summits in Western Tamil Nadu.',
    tier: 'platinum',
    displayOrder: 1,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'pt-2',
    category: 'partner',
    name: 'Tamil Nadu Chamber of Commerce & Industry',
    logoUrl: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=300&q=80',
    websiteUrl: 'https://example.com',
    description: 'Strategic Institutional Partner driving business delegate delegations and policy alignment.',
    tier: 'platinum',
    displayOrder: 2,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'pt-3',
    category: 'partner',
    name: 'Southern Digital Marketing Alliance',
    logoUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=300&q=80',
    websiteUrl: 'https://example.com',
    description: 'Collaborative marketing and influencer outreach syndicate.',
    tier: 'silver',
    displayOrder: 3,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },

  // Exhibitors
  {
    id: 'ex-1',
    category: 'exhibitor',
    name: 'Chai Kings & Quick Bites',
    logoUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=300&q=80',
    websiteUrl: 'https://example.com',
    description: 'Stall #A-14 | Quick Service Restaurant Franchise models ranging from ₹15L to ₹45L setup cost.',
    tier: 'general',
    displayOrder: 1,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'ex-2',
    category: 'exhibitor',
    name: 'Sparkle Laundromat Automated Systems',
    logoUrl: 'https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?auto=format&fit=crop&w=300&q=80',
    websiteUrl: 'https://example.com',
    description: 'Stall #B-08 | Smart IoT-connected commercial laundromat franchise opportunities.',
    tier: 'general',
    displayOrder: 2,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'ex-3',
    category: 'exhibitor',
    name: 'Aura Organic Superstores',
    logoUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=300&q=80',
    websiteUrl: 'https://example.com',
    description: 'Stall #C-02 | Farm-fresh organic grocery franchise network seeking regional master partners.',
    tier: 'general',
    displayOrder: 3,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'ex-4',
    category: 'exhibitor',
    name: 'NextGen Robotics Education Labs',
    logoUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=300&q=80',
    websiteUrl: 'https://example.com',
    description: 'Stall #D-11 | K-12 STEM, coding, and robotics school franchise curriculum solutions.',
    tier: 'general',
    displayOrder: 4,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
];

export const mockEvents: Event[] = [
  {
    id: 'evt-1',
    title: 'Tamil Nadu Business & Franchise Conclave 2026',
    slug: 'tamil-nadu-business-franchise-conclave-2026',
    description: 'Premier regional gathering connecting emerging business enterprises, commercial exhibitors, and trade delegations.',
    category: 'exhibition',
    status: 'upcoming',
    startDate: '2026-11-14T09:30:00Z',
    endDate: '2026-11-15T18:30:00Z',
    locationName: 'CODISSIA Trade Fair Complex',
    address: 'Avinashi Road, Peelamedu',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    country: 'India',
    bannerImage: '',
    organizerName: 'MCU Creations',
    organizerContact: '7010377731',
    ticketTypes: [
      {
        id: 't-1',
        name: 'Delegate Pass',
        price: 0,
        currency: 'INR',
        available: 500,
        description: 'Complimentary pass for business delegates and trade attendees.',
      },
    ],
    isFeatured: true,
    registrationOpen: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
];

export const mockServices: ServiceItem[] = [
  {
    id: 'srv-1',
    title: 'Event Management & Coordination',
    slug: 'event-management-coordination',
    shortDescription: 'Thoughtful planning, venue logistics, and stage coordination for corporate gatherings, exhibitions, and conclaves.',
    fullDescription: 'From spatial layout planning, stall coordination, and audiovisual staging to attendee registration helpdesks and guest management — MCU Creations brings dedicated energy to every event.',
    iconName: 'Calendar',
    features: [
      'Venue coordination & spatial layout planning',
      'Attendee registration setup & desk management',
      'Audio, lighting, and visual staging support',
      'On-site event coordination & support team',
    ],
    category: 'event_management',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'srv-2',
    title: 'Digital Marketing & Promotions',
    slug: 'digital-marketing-promotions',
    shortDescription: 'Targeted digital campaigns and marketing communication to promote events and connect with relevant audiences.',
    fullDescription: 'We help businesses and event organizers build awareness through targeted online promotions, clear messaging, and social outreach strategies designed to engage prospective attendees.',
    iconName: 'Megaphone',
    features: [
      'Social media promotional campaigns',
      'Targeted ad setup across Google and Meta platforms',
      'Event landing page and registration forms',
      'Audience communication & email/messaging updates',
    ],
    category: 'digital_marketing',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'srv-3',
    title: 'Social Media Engagement',
    slug: 'social-media-engagement',
    shortDescription: 'Creative visual content, reels, and active audience interaction focused on Instagram and Facebook.',
    fullDescription: 'Build an engaging social media presence on Instagram and Facebook. Our creative team produces visual content, event highlights, and social posts to foster authentic community connections.',
    iconName: 'Share2',
    features: [
      'Instagram reels & story highlight creation',
      'Facebook page management & regular posting',
      'Visual poster & promotional graphic design',
      'Event day photo/video moments capturing',
    ],
    category: 'social_media',
    displayOrder: 3,
    isActive: true,
  },
];

export const mockTestimonials: Testimonial[] = [
  {
    id: 't-1',
    clientName: 'Senthil Nathan',
    clientTitle: 'Managing Director',
    companyName: 'Kovai BioTech Equipments',
    content: 'MCU Creations transformed our annual trade summit. The visitor turnout was phenomenal, and the digitized badge scanning app generated over 450 verified distributor leads for our team in just two days.',
    rating: 5,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    displayOrder: 1,
    isFeatured: true,
  },
  {
    id: 't-2',
    clientName: 'Priya Sundarajan',
    clientTitle: 'Head of Marketing',
    companyName: 'Chai Kings Franchises',
    content: 'The digital marketing campaign executed by MCU for our stall was top-notch. Our booth was packed from 10 AM to 6 PM, and we signed 8 master franchise LOIs on the spot. Highly recommended event management team!',
    rating: 5,
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
    displayOrder: 2,
    isFeatured: true,
  },
  {
    id: 't-3',
    clientName: 'Dr. Anand Raman',
    clientTitle: 'Secretary',
    companyName: 'South India Healthcare Consortium',
    content: 'From stage production to audio clarity and international guest protocols, MCU Creations executed our 3-day medical symposium with world-class finesse. They are our permanent event partner.',
    rating: 5,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    displayOrder: 3,
    isFeatured: true,
  },
];

export const mockTeamMembers: TeamMember[] = [
  {
    id: 'tm-1',
    name: 'M. Ragul',
    role: 'Founder & Managing Director',
    bio: 'Visionary event strategist with over a decade of experience driving mega business expos, corporate conventions, and innovative digital marketing campaigns across South India.',
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    email: 'ragul@mcucreations.com',
    linkedinUrl: 'https://linkedin.com',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'tm-2',
    name: 'Karthik Raja',
    role: 'Director of Event Operations',
    bio: 'Expert in large-scale venue logistics, sound & lighting stage setups, vendor coordination, and disaster management protocols for trade fairs exceeding 20,000 visitors.',
    imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    email: 'operations@mcucreations.com',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'tm-3',
    name: 'Ananya Ramesh',
    role: 'Lead Digital Strategist & Media Producer',
    bio: 'Performance marketing specialist and creative storyteller managing multi-million impression ad campaigns and viral short-form video production.',
    imageUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
    email: 'marketing@mcucreations.com',
    displayOrder: 3,
    isActive: true,
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    id: 'blog-1',
    title: 'How to Maximize Exhibitor ROI at Business & Franchise Expos',
    slug: 'maximize-exhibitor-roi-franchise-expos',
    excerpt: 'Actionable strategies for stall design, pre-event digital outreach, interactive booth experiences, and rapid lead follow-up to turn footfall into revenue.',
    content: `
      <h2>The Anatomy of a High-Converting Expo Stall</h2>
      <p>Exhibiting at a major trade show or franchise summit is a significant investment. Yet, many exhibitors make the mistake of simply setting up a banner and sitting behind a table waiting for visitors to approach them.</p>
      
      <h3>1. Pre-Event Digital Retargeting</h3>
      <p>Don't wait for the expo doors to open. Run geo-fenced Meta and LinkedIn ad campaigns targeting delegates and business owners within a 50km radius 10 days before the expo, inviting them to book a specific 15-minute VIP slot at your booth.</p>
      
      <h3>2. Open-Flow Booth Architecture</h3>
      <p>Avoid placing tables directly at the entrance of your stall which acts as a psychological barrier. Instead, design an inviting open-concept walkthrough with interactive demo screens, sample displays, and comfortable discussion pods.</p>
      
      <h3>3. Digitize Lead Capture Instantly</h3>
      <p>Paper business cards get lost. Equip your booth staff with mobile QR scanners or digital lead capture apps so that lead data is automatically synced into your CRM with notes on budget and timeline within seconds.</p>
      
      <h3>4. The 24-Hour Follow-Up Rule</h3>
      <p>Hot leads turn cold rapidly after the expo buzz fades. Send a personalized WhatsApp greeting and email brochure within 24 hours while your presentation is fresh in the investor's mind.</p>
    `,
    coverImage: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80',
    authorName: 'MCU Marketing Team',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    category: 'Exhibitor Strategy',
    tags: ['Franchise', 'Stall Sales', 'B2B Marketing', 'Lead Generation'],
    isPublished: true,
    publishedAt: '2026-08-10T10:00:00Z',
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-08-10T10:00:00Z',
  },
  {
    id: 'blog-2',
    title: 'Short-Form Video & Reels: The Secret Weapon for Event Turnout',
    slug: 'short-form-video-reels-event-turnout',
    excerpt: 'Why high-velocity Instagram reels and creator collaborations outperform traditional billboards in driving paid ticket registrations.',
    content: `
      <h2>The Shift in Audience Discovery</h2>
      <p>Today's consumer and B2B delegate alike discover events not on roadside banners, but inside their vertical video feeds. A well-crafted 30-second teaser showing past crowd energy, celebrity speakers, and exclusive expo offers creates instant FOMO (Fear Of Missing Out).</p>
      
      <h3>Key Formula for Viral Event Teasers:</h3>
      <ul>
        <li><strong>Hook (0-3s):</strong> Start with an intriguing question or high-impact visual of the venue/crowd.</li>
        <li><strong>Value Proposition (3-15s):</strong> Show exactly what attendees will gain—franchise deals, networking, or masterclass certificates.</li>
        <li><strong>Clear Call to Action (15-30s):</strong> Direct viewers to click the bio link for early-bird tickets before slots run out.</li>
      </ul>
    `,
    coverImage: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&w=1200&q=80',
    authorName: 'Ananya Ramesh',
    authorAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80',
    category: 'Social Media',
    tags: ['Instagram Reels', 'Video Marketing', 'Ticket Sales', 'Viral Growth'],
    isPublished: true,
    publishedAt: '2026-08-04T10:00:00Z',
    createdAt: '2026-08-04T10:00:00Z',
    updatedAt: '2026-08-04T10:00:00Z',
  },
  {
    id: 'blog-3',
    title: 'Why Tier 2 Cities in Tamil Nadu are the Next Big Hub for B2B Expos',
    slug: 'tier-2-cities-tamil-nadu-b2b-expo-hubs',
    excerpt: 'Examining the rapid industrial and retail growth in Coimbatore, Madurai, Trichy, and Salem that makes regional summits so lucrative.',
    content: `
      <h2>Beyond the Metro Metros</h2>
      <p>While Chennai has traditionally hosted major state conventions, Tier 2 powerhouses like Coimbatore, Madurai, and Salem boast massive MSME clusters, textile giants, and burgeoning entrepreneurial ecosystems seeking expansion capital and franchise models.</p>
      
      <p>MCU Creations is proud to lead this revolution by delivering international-standard infrastructure, German hangar air-conditioned halls, and unified ticketing to every corner of Tamil Nadu.</p>
    `,
    coverImage: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80',
    authorName: 'M. Ragul',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    category: 'Industry Insights',
    tags: ['Tamil Nadu', 'Coimbatore', 'Business Growth', 'MSME'],
    isPublished: true,
    publishedAt: '2026-07-28T10:00:00Z',
    createdAt: '2026-07-28T10:00:00Z',
    updatedAt: '2026-07-28T10:00:00Z',
  },
];

export const mockGalleryItems: GalleryItem[] = [
  {
    id: 'gal-1',
    title: 'Grand Inauguration Ceremony & Lamp Lighting',
    caption: 'Dignitaries, Ministers, and Industry Presidents inaugurating the Business Expo.',
    imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80',
    category: 'Inauguration',
    displayOrder: 1,
    isFeatured: true,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'gal-2',
    title: 'Vibrant B2B Exhibitor Hall',
    caption: 'Over 150 stalls packed with delegates and business matchmaking sessions.',
    imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80',
    category: 'Exhibitions',
    displayOrder: 2,
    isFeatured: true,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'gal-3',
    title: 'Plenary Keynote Session & Masterclass Stage',
    caption: 'Full house audience attending the digital marketing & AI masterclass.',
    imageUrl: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=1200&q=80',
    category: 'Conferences',
    displayOrder: 3,
    isFeatured: true,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'gal-4',
    title: 'Gala Night & Excellence Awards Ceremony',
    caption: 'Honoring top franchise brands and outstanding exhibitor stall designs.',
    imageUrl: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1200&q=80',
    category: 'Awards',
    displayOrder: 4,
    isFeatured: true,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'gal-5',
    title: 'High-Impact LED Stage Setup',
    caption: 'Modular curved LED video wall and synchronized truss concert lighting.',
    imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1200&q=80',
    category: 'Stage Production',
    displayOrder: 5,
    isFeatured: false,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'gal-6',
    title: 'VIP Investor Lounge & Networking Banquet',
    caption: 'Exclusive lounge for C-level executives and international franchise delegates.',
    imageUrl: 'https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1200&q=80',
    category: 'VIP Networking',
    displayOrder: 6,
    isFeatured: false,
    createdAt: '2026-08-01T00:00:00Z',
  },
];

export const mockVideoHighlights: VideoItem[] = [
  {
    id: 'vid-1',
    title: 'Tamil Nadu Franchise Expo 2026 — Official Aftermovie & Highlights',
    description: 'Relive the electric atmosphere, key franchise announcements, and 10,000+ attendee experience captured in 4K.',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnailUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80',
    platform: 'youtube',
    displayOrder: 1,
    isFeatured: true,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'vid-2',
    title: 'Exhibitor Testimonial Sizzle Reel — CODISSIA Trade Complex',
    description: 'Top franchise CEOs share their experience and lead generation results with MCU Creations event management.',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80',
    platform: 'youtube',
    displayOrder: 2,
    isFeatured: true,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'vid-3',
    title: 'Digital Creators Conclave — Behind the Scenes & Stage Production',
    description: 'A peek into how our audiovisual crew, stage directors, and live stream engineers produce stadium-scale summits.',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnailUrl: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&w=1200&q=80',
    platform: 'youtube',
    displayOrder: 3,
    isFeatured: false,
    createdAt: '2026-08-01T00:00:00Z',
  },
];

export const mockRegistrations: EventRegistration[] = [
  {
    id: 'reg-101',
    eventId: 'evt-1',
    eventTitle: 'Tamil Nadu Franchise & Business Expo 2026',
    ticketTypeId: 't-1',
    registrationType: 'visitor',
    fullName: 'Anand Sundaram',
    email: 'anand.sundaram@investcoimbatore.in',
    phone: '+91 98430 11223',
    companyName: 'Kongu Retail Group',
    designation: 'Managing Partner',
    attendeesCount: 2,
    totalPrice: 0,
    status: 'confirmed',
    referenceCode: 'MCU-782190',
    notes: 'Interested in master franchise opportunities in FMCG sector.',
    createdAt: '2026-08-19T14:30:00Z',
  },
  {
    id: 'reg-102',
    eventId: 'evt-1',
    eventTitle: 'Tamil Nadu Franchise & Business Expo 2026',
    ticketTypeId: 't-2',
    registrationType: 'exhibitor',
    fullName: 'Priya Rajendran',
    email: 'priya.r@chennaibakes.com',
    phone: '+91 97909 88776',
    companyName: 'Madras Bakery Chains',
    designation: 'Head of Business Expansion',
    attendeesCount: 4,
    totalPrice: 15000,
    status: 'confirmed',
    referenceCode: 'MCU-445912',
    notes: 'Require 3x3 Octanorm booth space near food court pavilion.',
    createdAt: '2026-08-18T10:15:00Z',
  },
  {
    id: 'reg-103',
    eventId: 'evt-2',
    eventTitle: 'South India Digital Marketing Conclave 2026',
    ticketTypeId: 't-3',
    registrationType: 'visitor',
    fullName: 'Karthik Narayanan',
    email: 'karthik.n@growthfunnel.agency',
    phone: '+91 94441 55667',
    companyName: 'GrowthFunnel Digital',
    designation: 'Chief Marketing Officer',
    attendeesCount: 1,
    totalPrice: 2499,
    status: 'confirmed',
    referenceCode: 'MCU-993021',
    notes: 'Attending AI & Performance Ads Masterclass.',
    createdAt: '2026-08-17T16:45:00Z',
  },
  {
    id: 'reg-104',
    eventId: 'evt-1',
    eventTitle: 'Tamil Nadu Franchise & Business Expo 2026',
    ticketTypeId: 't-1',
    registrationType: 'visitor',
    fullName: 'Siddharth Varma',
    email: 'siddharth@varmaenterprises.com',
    phone: '+91 98840 99881',
    companyName: 'Varma Logistics & Warehousing',
    designation: 'Director',
    attendeesCount: 3,
    totalPrice: 0,
    status: 'pending',
    referenceCode: 'MCU-109283',
    notes: 'Looking for electric vehicle dealership franchises.',
    createdAt: '2026-08-16T11:20:00Z',
  },
  {
    id: 'reg-105',
    eventId: 'evt-3',
    eventTitle: 'Global Textile & Apparel Tech Expo 2026',
    ticketTypeId: 't-4',
    registrationType: 'visitor',
    fullName: 'Murugesan K.',
    email: 'murugesan@tirupurknits.org',
    phone: '+91 94433 22110',
    companyName: 'Tirupur Exporters Alliance',
    designation: 'Senior Vice President',
    attendeesCount: 5,
    totalPrice: 0,
    status: 'confirmed',
    referenceCode: 'MCU-623847',
    notes: 'Exploring sustainable dyeing and automated weaving machinery.',
    createdAt: '2026-08-15T09:00:00Z',
  },
];

export const mockEnquiries: Enquiry[] = [
  {
    id: 'enq-201',
    type: 'exhibitor',
    fullName: 'Ganesh Ramamurthy',
    email: 'ganesh.ram@texmach.in',
    phone: '+91 98422 77889',
    companyName: 'TexMach Automation Pvt Ltd',
    designation: 'Managing Director',
    subject: 'Stall Booking for Textile Tech Expo 2026',
    message: 'We want to reserve a 36 sq.m Bare Island Stall in Hall B for heavy circular knitting machinery demo.',
    eventId: 'evt-3',
    eventName: 'Global Textile & Apparel Tech Expo 2026',
    status: 'new',
    metadata: { stallSize: '36 sqm', powerRequirement: '25 kW 3-phase' },
    createdAt: '2026-08-19T17:10:00Z',
  },
  {
    id: 'enq-202',
    type: 'sponsor',
    fullName: 'Lakshmi Narayan',
    email: 'lakshmi.n@finvestcapital.com',
    phone: '+91 99620 44332',
    companyName: 'FinVest Capital South',
    designation: 'Head of Corporate Alliances',
    subject: 'Gold Sponsorship Proposal — Franchise Expo 2026',
    message: 'We would like to explore Gold Associate Sponsorship with VIP lounge branding and delegate bag inserts.',
    eventId: 'evt-1',
    eventName: 'Tamil Nadu Franchise & Business Expo 2026',
    status: 'in_progress',
    metadata: { sponsorshipBudget: '₹5,00,000', deliverables: ['VIP Lounge', 'Bag Inserts'] },
    createdAt: '2026-08-18T14:25:00Z',
  },
  {
    id: 'enq-203',
    type: 'digital_marketing',
    fullName: 'Dinesh Kumar',
    email: 'dinesh@kovaijewels.com',
    phone: '+91 97890 12345',
    companyName: 'Kovai Heritage Jewellers',
    designation: 'Marketing Head',
    subject: 'Omnichannel Performance Marketing for Festive Season',
    message: 'Looking for full-funnel Meta and Google Ads management + viral influencer reels production across Coimbatore & Salem.',
    status: 'new',
    metadata: { monthlyAdSpend: '₹3,00,000', targetLocations: ['Coimbatore', 'Salem', 'Erode'] },
    createdAt: '2026-08-18T09:40:00Z',
  },
  {
    id: 'enq-204',
    type: 'partnership',
    fullName: 'Prof. R. Chandrasekar',
    email: 'r.chandrasekar@psgtech.edu',
    phone: '+91 94421 88990',
    companyName: 'PSG Institute of Management',
    designation: 'Director — Industry Collaborations',
    subject: 'Academic & Knowledge Partnership for AI Conclave',
    message: 'Proposing faculty panel participation and 50 student delegate sponsorships for the Digital Creators Conclave.',
    eventId: 'evt-4',
    eventName: 'Digital Creators & Social Media Conclave 2026',
    status: 'contacted',
    createdAt: '2026-08-17T15:00:00Z',
  },
  {
    id: 'enq-205',
    type: 'event',
    fullName: 'Meera Vijayakumar',
    email: 'meera.v@naturalsfranchise.in',
    phone: '+91 98401 22334',
    companyName: 'Naturals Salon Franchise Network',
    designation: 'Franchise Relations Manager',
    subject: 'Speaker Slot & Masterclass Request',
    message: 'Our founder would like to deliver a 30-minute keynote on "Scaling Salon Chains to Tier-2 Cities".',
    eventId: 'evt-1',
    eventName: 'Tamil Nadu Franchise & Business Expo 2026',
    status: 'resolved',
    createdAt: '2026-08-16T12:30:00Z',
  },
];

