import { Event, BlogPost, EntityPartner, ServiceItem, Testimonial, TeamMember, GalleryItem, VideoItem, EventRegistration, Enquiry } from '@/types';

export const mockPartners: EntityPartner[] = [
  // Sponsors
  {
    id: 'sp-1',
    category: 'sponsor',
    name: 'Apex Global Financial Services',
    logoUrl: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&w=300&q=80',
    websiteUrl: 'https://example.com',
    description: 'Title Platinum Sponsor powering enterprise MSME loan distribution at MCU expos.',
    tier: 'platinum',
    displayOrder: 1,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'sp-2',
    category: 'sponsor',
    name: 'Vanguard Tech Infra',
    logoUrl: 'https://images.unsplash.com/photo-1516876437184-593fda40c7ce?auto=format&fit=crop&w=300&q=80',
    websiteUrl: 'https://example.com',
    description: 'Official Gold Sponsor providing cloud POS infrastructure and high-speed venue mesh networks.',
    tier: 'gold',
    displayOrder: 2,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'sp-3',
    category: 'sponsor',
    name: 'Kovai Fresh Beverages',
    logoUrl: 'https://images.unsplash.com/photo-1551836022-deb4988cc6c0?auto=format&fit=crop&w=300&q=80',
    websiteUrl: 'https://example.com',
    description: 'Official Beverage Partner offering refreshments across VIP lounges and exhibitor stalls.',
    tier: 'silver',
    displayOrder: 3,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'sp-4',
    category: 'sponsor',
    name: 'The Hindu Businessline',
    logoUrl: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=300&q=80',
    websiteUrl: 'https://example.com',
    description: 'Official Print & Digital Media Partner delivering statewide event coverage.',
    tier: 'media',
    displayOrder: 4,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },

  // Strategic Partners
  {
    id: 'pt-1',
    category: 'partner',
    name: 'CODISSIA Trade Center',
    logoUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=300&q=80',
    websiteUrl: 'https://example.com',
    description: 'Official Venue Partner hosting premier exhibitions and summits in Western Tamil Nadu.',
    tier: 'platinum',
    displayOrder: 1,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'pt-2',
    category: 'partner',
    name: 'Tamil Nadu Chamber of Commerce & Industry',
    logoUrl: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=300&q=80',
    websiteUrl: 'https://example.com',
    description: 'Strategic Institutional Partner driving business delegate delegations and policy alignment.',
    tier: 'platinum',
    displayOrder: 2,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'pt-3',
    category: 'partner',
    name: 'Southern Digital Marketing Alliance',
    logoUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=300&q=80',
    websiteUrl: 'https://example.com',
    description: 'Collaborative marketing and influencer outreach syndicate.',
    tier: 'silver',
    displayOrder: 3,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },

  // Exhibitors
  {
    id: 'ex-1',
    category: 'exhibitor',
    name: 'Chai Kings & Quick Bites',
    logoUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=300&q=80',
    websiteUrl: 'https://example.com',
    description: 'Stall #A-14 | Quick Service Restaurant Franchise models ranging from ₹15L to ₹45L setup cost.',
    tier: 'general',
    displayOrder: 1,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'ex-2',
    category: 'exhibitor',
    name: 'Sparkle Laundromat Automated Systems',
    logoUrl: 'https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?auto=format&fit=crop&w=300&q=80',
    websiteUrl: 'https://example.com',
    description: 'Stall #B-08 | Smart IoT-connected commercial laundromat franchise opportunities.',
    tier: 'general',
    displayOrder: 2,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'ex-3',
    category: 'exhibitor',
    name: 'Aura Organic Superstores',
    logoUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=300&q=80',
    websiteUrl: 'https://example.com',
    description: 'Stall #C-02 | Farm-fresh organic grocery franchise network seeking regional master partners.',
    tier: 'general',
    displayOrder: 3,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'ex-4',
    category: 'exhibitor',
    name: 'NextGen Robotics Education Labs',
    logoUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=300&q=80',
    websiteUrl: 'https://example.com',
    description: 'Stall #D-11 | K-12 STEM, coding, and robotics school franchise curriculum solutions.',
    tier: 'general',
    displayOrder: 4,
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
];

export const mockEvents: Event[] = [
  {
    id: 'evt-1',
    title: 'Tamil Nadu Franchise & Business Expo 2026',
    slug: 'tamil-nadu-franchise-expo-2026',
    description: 'South India’s largest B2B franchise and business opportunities summit. Connect with 150+ national brands, retail giants, master franchises, and investor networks.',
    content: `
      <h3>The Region's Premier Franchise & Investment Summit</h3>
      <p>The Tamil Nadu Franchise & Business Expo 2026 brings together budding entrepreneurs, seasoned investors, and top national/international brands across Retail, F&B, Education, Healthcare, and Technology sectors under one roof.</p>
      
      <h4>Key Highlights:</h4>
      <ul>
        <li>150+ Top Franchise Brands across 25+ business sectors</li>
        <li>10,000+ Verified Business Investors & Entrepreneurs</li>
        <li>Keynote Masterclasses by industry pioneers & franchise consultants</li>
        <li>1-on-1 Investor Pitching Lounges and direct franchise sign-ups</li>
        <li>Exhibitor awards ceremony & VIP networking banquet</li>
      </ul>
      
      <h4>Event Schedule:</h4>
      <p><strong>Day 1 (Sep 12):</strong> Inaugural Ceremony, Franchise Growth Panel, Investor Pitch Sessions (09:30 AM - 06:00 PM)</p>
      <p><strong>Day 2 (Sep 13):</strong> Brand Matchmaking, Legal & Funding Workshop, Gala Awards Night (10:00 AM - 06:30 PM)</p>
    `,
    category: 'exhibition',
    status: 'upcoming',
    startDate: '2026-09-12T09:00:00Z',
    endDate: '2026-09-13T18:30:00Z',
    locationName: 'CODISSIA Trade Fair Complex',
    address: 'GV Fair Grounds, Avinashi Road',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    country: 'India',
    bannerImage: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1200&q=80',
    ],
    organizerName: 'MCU Creations',
    organizerContact: '+91 98421 88900',
    organizerEmail: 'events@mcucreations.com',
    googleMapsUrl: 'https://maps.google.com/?q=CODISSIA+Trade+Fair+Complex+Coimbatore',
    ticketTypes: [
      {
        id: 't-1',
        name: 'Visitor / Delegate Pass',
        price: 299,
        currency: 'INR',
        available: 850,
        description: '2-Day access to exhibition hall, brand presentations, and business directory catalog.',
      },
      {
        id: 't-2',
        name: 'VIP Investor Pass',
        price: 1499,
        currency: 'INR',
        available: 120,
        description: 'VIP Lounge access, priority B2B matchmaking, speaker lounge lunch, and verified franchise kits.',
      },
      {
        id: 't-3',
        name: 'Masterclass Workshop Add-On',
        price: 999,
        currency: 'INR',
        available: 60,
        description: 'Exclusive 3-hour intensive workshop on Franchise Legalities, ROI Models & Funding.',
      },
    ],
    highlights: [
      {
        title: '150+ Franchise Brands',
        description: 'Meet verified franchise franchisors across F&B, Retail, Services & Tech.',
        iconName: 'Building',
      },
      {
        title: '10,000+ Business Buyers',
        description: 'Direct access to verified high-net-worth investors and prospective franchisees.',
        iconName: 'Users',
      },
      {
        title: '₹50Cr+ Projected LOIs',
        description: 'On-the-spot matchmaking and business agreement signing facilities.',
        iconName: 'TrendingUp',
      },
      {
        title: 'Masterclass Workshops',
        description: 'Learn legal, funding, and marketing strategies from industry experts.',
        iconName: 'Award',
      },
    ],
    speakers: [
      {
        id: 'spk-1',
        name: 'Rajesh Subramaniam',
        role: 'Franchise Growth Consultant & Author',
        company: 'RetailScale Advisory',
        bio: 'Over 18 years helping regional retail chains scale to 200+ outlets nationwide.',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
        linkedinUrl: 'https://linkedin.com',
      },
      {
        id: 'spk-2',
        name: 'Deepa Krishnan',
        role: 'Founder & CEO',
        company: 'Kovai Fresh Cafe Chain',
        bio: 'Built a 60-store franchise network across South India with zero external equity.',
        avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
        linkedinUrl: 'https://linkedin.com',
      },
      {
        id: 'spk-3',
        name: 'K. Venkatesh',
        role: 'Head of MSME Banking',
        company: 'Apex Global Financial Services',
        bio: 'Spearheading government credit schemes, CGTMSE loan structuring, and angel syndicates.',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
        linkedinUrl: 'https://linkedin.com',
      },
    ],
    faqs: [
      {
        question: 'What are the expo timings on both days?',
        answer: 'The expo exhibition hall will remain open from 09:30 AM to 06:30 PM on September 12 and 13, 2026. Plenary keynote sessions start promptly at 10:30 AM.',
      },
      {
        question: 'How do I receive my event delegate pass?',
        answer: 'Upon submitting your registration online, a verified pass reference ID is issued immediately. Digital badges with QR codes are also emailed to you for express lane entry.',
      },
      {
        question: 'Are spot registrations available at CODISSIA?',
        answer: 'Yes, spot registration counters will be active at Gate 3. However, online pre-registration is recommended to skip on-site queues and guarantee delegate kit availability.',
      },
      {
        question: 'How can our company book an exhibitor stall?',
        answer: 'You can submit an Exhibitor Enquiry through the "Become an Exhibitor" button above or email events@mcucreations.com. Our floor coordinator will share available stall schemes and the hall layout.',
      },
    ],
    sponsors: [mockPartners[0], mockPartners[1], mockPartners[2], mockPartners[3]],
    exhibitors: [mockPartners[7], mockPartners[8], mockPartners[9], mockPartners[10]],
    partners: [mockPartners[4], mockPartners[5], mockPartners[6]],
    isFeatured: true,
    registrationOpen: true,
    registrationEnabled: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-15T00:00:00Z',
  },
  {
    id: 'evt-2',
    title: 'South India MSME & Retail Conclave 2026',
    slug: 'south-india-msme-retail-conclave-2026',
    description: 'Empowering small and medium enterprises with cutting-edge retail technology, supply chain modernization, and direct access to banking & NBFC lines of credit.',
    content: `
      <h3>Accelerating Enterprise Scale Across South India</h3>
      <p>A flagship leadership conference designed for manufacturing leaders, retail store chain owners, and digital-first D2C brands.</p>
      <h4>Focus Areas:</h4>
      <ul>
        <li>Omnichannel Retail Automation & AI POS systems</li>
        <li>MSME Subsidies, Export Credit & Govt Grant Navigation</li>
        <li>Supply Chain Optimization for Tier 2 & Tier 3 hubs</li>
      </ul>
    `,
    category: 'conference',
    status: 'upcoming',
    startDate: '2026-10-08T09:30:00Z',
    endDate: '2026-10-09T17:30:00Z',
    locationName: 'Chennai Trade Centre (CTC)',
    address: 'Nandambakkam, Mount Poonamallee Road',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    bannerImage: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1200&q=80',
    ],
    organizerName: 'MCU Creations in Association with TN Chamber',
    organizerContact: '+91 98421 88901',
    organizerEmail: 'conclave@mcucreations.com',
    googleMapsUrl: 'https://maps.google.com/?q=Chennai+Trade+Centre+Nandambakkam',
    ticketTypes: [
      {
        id: 't-4',
        name: 'Conference Delegate Pass',
        price: 799,
        currency: 'INR',
        available: 400,
        description: 'Access to all keynote stages, panel tracks, networking lunch, and delegate kit.',
      },
      {
        id: 't-5',
        name: 'Corporate Delegation (3 Members)',
        price: 1999,
        currency: 'INR',
        available: 80,
        description: 'Includes 3 full delegate passes with reserved seating in plenary tracks.',
      },
    ],
    speakers: [
      {
        id: 'spk-4',
        name: 'Dr. Anand Raman',
        role: 'Industrial Economist',
        company: 'Tamil Nadu Chamber of Commerce',
        bio: 'Advisor to state trade ministries on industrial corridor developments and MSME subsidies.',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
        linkedinUrl: 'https://linkedin.com',
      },
    ],
    faqs: [
      {
        question: 'Will networking lunch be provided?',
        answer: 'Yes, all registered delegate passes include executive networking buffet lunches and tea breaks on both conference days.',
      },
      {
        question: 'Can I transfer my pass to a colleague if I cannot attend?',
        answer: 'Yes, passes can be re-assigned up to 48 hours before the event date by contacting conclave@mcucreations.com.',
      },
    ],
    sponsors: [mockPartners[0], mockPartners[1]],
    partners: [mockPartners[5]],
    isFeatured: true,
    registrationOpen: true,
    registrationEnabled: true,
    createdAt: '2026-08-05T00:00:00Z',
    updatedAt: '2026-08-16T00:00:00Z',
  },
  {
    id: 'evt-3',
    title: 'Future Mobility & Clean Energy Expo 2026',
    slug: 'future-mobility-clean-energy-expo-2026',
    description: 'Showcasing commercial EVs, battery tech breakthroughs, charging infrastructure networks, and green solar energy solutions.',
    content: `
      <h3>Next-Gen Sustainable Transportation & Power</h3>
      <p>Join 80+ EV manufacturers, solar innovators, and government policy makers in Tamil Nadu's industrial heartland.</p>
    `,
    category: 'exhibition',
    status: 'upcoming',
    startDate: '2026-11-20T10:00:00Z',
    endDate: '2026-11-22T18:00:00Z',
    locationName: 'Madurai Convention Centre',
    address: 'Ring Road, Near Airport Junction',
    city: 'Madurai',
    state: 'Tamil Nadu',
    country: 'India',
    bannerImage: 'https://images.unsplash.com/photo-1558441719-646b22ad8997?auto=format&fit=crop&w=1600&q=80',
    organizerName: 'MCU Creations',
    organizerContact: '+91 98421 88902',
    organizerEmail: 'mobility@mcucreations.com',
    googleMapsUrl: 'https://maps.google.com/?q=Madurai+Convention+Centre',
    ticketTypes: [
      {
        id: 't-6',
        name: 'Trade Visitor Pass',
        price: 0,
        currency: 'INR',
        available: 2000,
        description: 'Complimentary pass for registered industry professionals and automotive enthusiasts.',
      },
      {
        id: 't-7',
        name: 'Buyer-Seller VIP Lounge',
        price: 899,
        currency: 'INR',
        available: 150,
        description: 'Dedicated lounge access, high-speed WiFi, coffee bar, and direct B2B vendor directory.',
      },
    ],
    isFeatured: true,
    registrationOpen: true,
    registrationEnabled: true,
    createdAt: '2026-08-10T00:00:00Z',
    updatedAt: '2026-08-18T00:00:00Z',
  },
  {
    id: 'evt-4',
    title: 'Creators Conclave & Digital Growth Summit',
    slug: 'creators-conclave-digital-growth-summit',
    description: 'The mega gathering of top content creators, social media influencers, digital marketers, and brand marketing heads.',
    content: `
      <h3>Mastering Social Media Algorithms & Viral Production</h3>
      <p>High-energy workshops on short-form video monetization, influencer marketing ROI, brand collabs, and generative AI content creation tools.</p>
    `,
    category: 'workshop',
    status: 'upcoming',
    startDate: '2026-12-05T10:00:00Z',
    endDate: '2026-12-05T19:00:00Z',
    locationName: 'ITC Grand Chola Banquet Pavilion',
    address: 'Guindy',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    bannerImage: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&w=1600&q=80',
    organizerName: 'MCU Creations & Digital Wings',
    organizerContact: '+91 98421 88903',
    organizerEmail: 'creators@mcucreations.com',
    googleMapsUrl: 'https://maps.google.com/?q=ITC+Grand+Chola+Chennai',
    ticketTypes: [
      {
        id: 't-8',
        name: 'Creator Standard Pass',
        price: 599,
        currency: 'INR',
        available: 300,
        description: 'Full day access to live creator stages, panel keynotes, and photo booths.',
      },
      {
        id: 't-9',
        name: 'VIP Creator & Agency Pass',
        price: 1999,
        currency: 'INR',
        available: 50,
        description: 'Backstage networking with speakers, 1-on-1 brand sponsorship pitch slots, and after-party.',
      },
    ],
    isFeatured: false,
    registrationOpen: true,
    registrationEnabled: true,
    createdAt: '2026-08-12T00:00:00Z',
    updatedAt: '2026-08-18T00:00:00Z',
  },
  {
    id: 'evt-past-1',
    title: 'Tamil Nadu Franchise & Retail Summit 2025',
    slug: 'tamil-nadu-franchise-retail-summit-2025',
    description: 'The 2025 edition gathered 120+ franchise brands and over 8,500 entrepreneurs with ₹35Cr+ in signed LOIs across South India.',
    content: `
      <h3>Flagship 2025 Retrospective</h3>
      <p>The 2025 summit established MCU Creations as the definitive B2B exhibition platform in Western Tamil Nadu.</p>
    `,
    category: 'exhibition',
    status: 'completed',
    startDate: '2025-08-23T09:00:00Z',
    endDate: '2025-08-24T18:00:00Z',
    locationName: 'CODISSIA Trade Fair Complex',
    address: 'Avinashi Road',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    country: 'India',
    bannerImage: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1200&q=80',
    ],
    organizerName: 'MCU Creations',
    organizerContact: 'events@mcucreations.com',
    ticketTypes: [
      {
        id: 't-past-1',
        name: 'Standard Delegate Pass',
        price: 299,
        currency: 'INR',
        available: 0,
        description: 'Event concluded.',
      },
    ],
    isFeatured: false,
    registrationOpen: false,
    registrationEnabled: false,
    createdAt: '2025-07-01T00:00:00Z',
    updatedAt: '2025-08-25T00:00:00Z',
  },
  {
    id: 'evt-past-2',
    title: 'South India Brand & Creator Awards 2025',
    slug: 'south-india-brand-creator-awards-2025',
    description: 'Celebrating 50+ outstanding regional marketing campaigns, influencer collaborations, and franchise success stories.',
    content: `
      <h3>Honoring Regional Excellence</h3>
      <p>A star-studded evening featuring top brand CEOs, celebrity creators, and industry presidents.</p>
    `,
    category: 'corporate',
    status: 'completed',
    startDate: '2025-11-15T18:00:00Z',
    endDate: '2025-11-15T22:30:00Z',
    locationName: 'Le Meridien Grand Ballroom',
    address: 'Neelambur',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    country: 'India',
    bannerImage: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1600&q=80',
    organizerName: 'MCU Creations',
    organizerContact: 'events@mcucreations.com',
    ticketTypes: [
      {
        id: 't-past-2',
        name: 'Gala Dinner Pass',
        price: 1999,
        currency: 'INR',
        available: 0,
        description: 'Event concluded.',
      },
    ],
    isFeatured: false,
    registrationOpen: false,
    registrationEnabled: false,
    createdAt: '2025-10-01T00:00:00Z',
    updatedAt: '2025-11-16T00:00:00Z',
  },
  {
    id: 'evt-draft-1',
    title: 'Upcoming Internal Draft Expo (Preview Only)',
    slug: 'internal-draft-expo-2027',
    description: 'This is an unreleased internal draft that must NOT be publicly visible.',
    category: 'exhibition',
    status: 'draft',
    startDate: '2027-01-01T00:00:00Z',
    endDate: '2027-01-02T00:00:00Z',
    locationName: 'TBD',
    address: 'TBD',
    city: 'Chennai',
    bannerImage: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80',
    organizerName: 'MCU Admin',
    organizerContact: 'admin@mcucreations.com',
    ticketTypes: [],
    isFeatured: false,
    registrationOpen: false,
    registrationEnabled: false,
    createdAt: '2026-08-19T00:00:00Z',
    updatedAt: '2026-08-19T00:00:00Z',
  },
];

export const mockServices: ServiceItem[] = [
  {
    id: 'srv-1',
    title: 'Event Management & Coordination',
    slug: 'event-management-coordination',
    shortDescription: 'Thoughtful planning, venue logistics, and stage coordination for corporate gatherings, exhibitions, and conclaves.',
    fullDescription: 'From spatial layout planning, stall coordination, and audiovisual staging to attendee registration helpdesks and guest management — MCU Creations brings dedicated energy to every event.',
    iconName: 'Calendar',
    features: [
      'Venue coordination & spatial layout planning',
      'Attendee registration setup & desk management',
      'Audio, lighting, and visual staging support',
      'On-site event coordination & support team',
    ],
    category: 'event_management',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'srv-2',
    title: 'Digital Marketing & Promotions',
    slug: 'digital-marketing-promotions',
    shortDescription: 'Targeted digital campaigns and marketing communication to promote events and connect with relevant audiences.',
    fullDescription: 'We help businesses and event organizers build awareness through targeted online promotions, clear messaging, and social outreach strategies designed to engage prospective attendees.',
    iconName: 'Megaphone',
    features: [
      'Social media promotional campaigns',
      'Targeted ad setup across Google and Meta platforms',
      'Event landing page and registration forms',
      'Audience communication & email/messaging updates',
    ],
    category: 'digital_marketing',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'srv-3',
    title: 'Social Media Engagement',
    slug: 'social-media-engagement',
    shortDescription: 'Creative visual content, reels, and active audience interaction focused on Instagram and Facebook.',
    fullDescription: 'Build an engaging social media presence on Instagram and Facebook. Our creative team produces visual content, event highlights, and social posts to foster authentic community connections.',
    iconName: 'Share2',
    features: [
      'Instagram reels & story highlight creation',
      'Facebook page management & regular posting',
      'Visual poster & promotional graphic design',
      'Event day photo/video moments capturing',
    ],
    category: 'social_media',
    displayOrder: 3,
    isActive: true,
  },
];

export const mockTestimonials: Testimonial[] = [
  {
    id: 't-1',
    clientName: 'Senthil Nathan',
    clientTitle: 'Managing Director',
    companyName: 'Kovai BioTech Equipments',
    content: 'MCU Creations transformed our annual trade summit. The visitor turnout was phenomenal, and the digitized badge scanning app generated over 450 verified distributor leads for our team in just two days.',
    rating: 5,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    displayOrder: 1,
    isFeatured: true,
  },
  {
    id: 't-2',
    clientName: 'Priya Sundarajan',
    clientTitle: 'Head of Marketing',
    companyName: 'Chai Kings Franchises',
    content: 'The digital marketing campaign executed by MCU for our stall was top-notch. Our booth was packed from 10 AM to 6 PM, and we signed 8 master franchise LOIs on the spot. Highly recommended event management team!',
    rating: 5,
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
    displayOrder: 2,
    isFeatured: true,
  },
  {
    id: 't-3',
    clientName: 'Dr. Anand Raman',
    clientTitle: 'Secretary',
    companyName: 'South India Healthcare Consortium',
    content: 'From stage production to audio clarity and international guest protocols, MCU Creations executed our 3-day medical symposium with world-class finesse. They are our permanent event partner.',
    rating: 5,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    displayOrder: 3,
    isFeatured: true,
  },
];

export const mockTeamMembers: TeamMember[] = [
  {
    id: 'tm-1',
    name: 'M. Ragul',
    role: 'Founder & Managing Director',
    bio: 'Visionary event strategist with over a decade of experience driving mega business expos, corporate conventions, and innovative digital marketing campaigns across South India.',
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    email: 'ragul@mcucreations.com',
    linkedinUrl: 'https://linkedin.com',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'tm-2',
    name: 'Karthik Raja',
    role: 'Director of Event Operations',
    bio: 'Expert in large-scale venue logistics, sound & lighting stage setups, vendor coordination, and disaster management protocols for trade fairs exceeding 20,000 visitors.',
    imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    email: 'operations@mcucreations.com',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'tm-3',
    name: 'Ananya Ramesh',
    role: 'Lead Digital Strategist & Media Producer',
    bio: 'Performance marketing specialist and creative storyteller managing multi-million impression ad campaigns and viral short-form video production.',
    imageUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
    email: 'marketing@mcucreations.com',
    displayOrder: 3,
    isActive: true,
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    id: 'blog-1',
    title: 'How to Maximize Exhibitor ROI at Business & Franchise Expos',
    slug: 'maximize-exhibitor-roi-franchise-expos',
    excerpt: 'Actionable strategies for stall design, pre-event digital outreach, interactive booth experiences, and rapid lead follow-up to turn footfall into revenue.',
    content: `
      <h2>The Anatomy of a High-Converting Expo Stall</h2>
      <p>Exhibiting at a major trade show or franchise summit is a significant investment. Yet, many exhibitors make the mistake of simply setting up a banner and sitting behind a table waiting for visitors to approach them.</p>
      
      <h3>1. Pre-Event Digital Retargeting</h3>
      <p>Don't wait for the expo doors to open. Run geo-fenced Meta and LinkedIn ad campaigns targeting delegates and business owners within a 50km radius 10 days before the expo, inviting them to book a specific 15-minute VIP slot at your booth.</p>
      
      <h3>2. Open-Flow Booth Architecture</h3>
      <p>Avoid placing tables directly at the entrance of your stall which acts as a psychological barrier. Instead, design an inviting open-concept walkthrough with interactive demo screens, sample displays, and comfortable discussion pods.</p>
      
      <h3>3. Digitize Lead Capture Instantly</h3>
      <p>Paper business cards get lost. Equip your booth staff with mobile QR scanners or digital lead capture apps so that lead data is automatically synced into your CRM with notes on budget and timeline within seconds.</p>
      
      <h3>4. The 24-Hour Follow-Up Rule</h3>
      <p>Hot leads turn cold rapidly after the expo buzz fades. Send a personalized WhatsApp greeting and email brochure within 24 hours while your presentation is fresh in the investor's mind.</p>
    `,
    coverImage: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80',
    authorName: 'MCU Marketing Team',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    category: 'Exhibitor Strategy',
    tags: ['Franchise', 'Stall Sales', 'B2B Marketing', 'Lead Generation'],
    isPublished: true,
    publishedAt: '2026-08-10T10:00:00Z',
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-08-10T10:00:00Z',
  },
  {
    id: 'blog-2',
    title: 'Short-Form Video & Reels: The Secret Weapon for Event Turnout',
    slug: 'short-form-video-reels-event-turnout',
    excerpt: 'Why high-velocity Instagram reels and creator collaborations outperform traditional billboards in driving paid ticket registrations.',
    content: `
      <h2>The Shift in Audience Discovery</h2>
      <p>Today's consumer and B2B delegate alike discover events not on roadside banners, but inside their vertical video feeds. A well-crafted 30-second teaser showing past crowd energy, celebrity speakers, and exclusive expo offers creates instant FOMO (Fear Of Missing Out).</p>
      
      <h3>Key Formula for Viral Event Teasers:</h3>
      <ul>
        <li><strong>Hook (0-3s):</strong> Start with an intriguing question or high-impact visual of the venue/crowd.</li>
        <li><strong>Value Proposition (3-15s):</strong> Show exactly what attendees will gain—franchise deals, networking, or masterclass certificates.</li>
        <li><strong>Clear Call to Action (15-30s):</strong> Direct viewers to click the bio link for early-bird tickets before slots run out.</li>
      </ul>
    `,
    coverImage: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&w=1200&q=80',
    authorName: 'Ananya Ramesh',
    authorAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80',
    category: 'Social Media',
    tags: ['Instagram Reels', 'Video Marketing', 'Ticket Sales', 'Viral Growth'],
    isPublished: true,
    publishedAt: '2026-08-04T10:00:00Z',
    createdAt: '2026-08-04T10:00:00Z',
    updatedAt: '2026-08-04T10:00:00Z',
  },
  {
    id: 'blog-3',
    title: 'Why Tier 2 Cities in Tamil Nadu are the Next Big Hub for B2B Expos',
    slug: 'tier-2-cities-tamil-nadu-b2b-expo-hubs',
    excerpt: 'Examining the rapid industrial and retail growth in Coimbatore, Madurai, Trichy, and Salem that makes regional summits so lucrative.',
    content: `
      <h2>Beyond the Metro Metros</h2>
      <p>While Chennai has traditionally hosted major state conventions, Tier 2 powerhouses like Coimbatore, Madurai, and Salem boast massive MSME clusters, textile giants, and burgeoning entrepreneurial ecosystems seeking expansion capital and franchise models.</p>
      
      <p>MCU Creations is proud to lead this revolution by delivering international-standard infrastructure, German hangar air-conditioned halls, and unified ticketing to every corner of Tamil Nadu.</p>
    `,
    coverImage: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80',
    authorName: 'M. Ragul',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    category: 'Industry Insights',
    tags: ['Tamil Nadu', 'Coimbatore', 'Business Growth', 'MSME'],
    isPublished: true,
    publishedAt: '2026-07-28T10:00:00Z',
    createdAt: '2026-07-28T10:00:00Z',
    updatedAt: '2026-07-28T10:00:00Z',
  },
];

export const mockGalleryItems: GalleryItem[] = [
  {
    id: 'gal-1',
    title: 'Grand Inauguration Ceremony & Lamp Lighting',
    caption: 'Dignitaries, Ministers, and Industry Presidents inaugurating the Business Expo.',
    imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80',
    category: 'Inauguration',
    displayOrder: 1,
    isFeatured: true,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'gal-2',
    title: 'Vibrant B2B Exhibitor Hall',
    caption: 'Over 150 stalls packed with delegates and business matchmaking sessions.',
    imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80',
    category: 'Exhibitions',
    displayOrder: 2,
    isFeatured: true,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'gal-3',
    title: 'Plenary Keynote Session & Masterclass Stage',
    caption: 'Full house audience attending the digital marketing & AI masterclass.',
    imageUrl: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=1200&q=80',
    category: 'Conferences',
    displayOrder: 3,
    isFeatured: true,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'gal-4',
    title: 'Gala Night & Excellence Awards Ceremony',
    caption: 'Honoring top franchise brands and outstanding exhibitor stall designs.',
    imageUrl: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1200&q=80',
    category: 'Awards',
    displayOrder: 4,
    isFeatured: true,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'gal-5',
    title: 'High-Impact LED Stage Setup',
    caption: 'Modular curved LED video wall and synchronized truss concert lighting.',
    imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1200&q=80',
    category: 'Stage Production',
    displayOrder: 5,
    isFeatured: false,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'gal-6',
    title: 'VIP Investor Lounge & Networking Banquet',
    caption: 'Exclusive lounge for C-level executives and international franchise delegates.',
    imageUrl: 'https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1200&q=80',
    category: 'VIP Networking',
    displayOrder: 6,
    isFeatured: false,
    createdAt: '2026-08-01T00:00:00Z',
  },
];

export const mockVideoHighlights: VideoItem[] = [
  {
    id: 'vid-1',
    title: 'Tamil Nadu Franchise Expo 2026 — Official Aftermovie & Highlights',
    description: 'Relive the electric atmosphere, key franchise announcements, and 10,000+ attendee experience captured in 4K.',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnailUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80',
    platform: 'youtube',
    displayOrder: 1,
    isFeatured: true,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'vid-2',
    title: 'Exhibitor Testimonial Sizzle Reel — CODISSIA Trade Complex',
    description: 'Top franchise CEOs share their experience and lead generation results with MCU Creations event management.',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80',
    platform: 'youtube',
    displayOrder: 2,
    isFeatured: true,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'vid-3',
    title: 'Digital Creators Conclave — Behind the Scenes & Stage Production',
    description: 'A peek into how our audiovisual crew, stage directors, and live stream engineers produce stadium-scale summits.',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnailUrl: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&w=1200&q=80',
    platform: 'youtube',
    displayOrder: 3,
    isFeatured: false,
    createdAt: '2026-08-01T00:00:00Z',
  },
];

export const mockRegistrations: EventRegistration[] = [
  {
    id: 'reg-101',
    eventId: 'evt-1',
    eventTitle: 'Tamil Nadu Franchise & Business Expo 2026',
    ticketTypeId: 't-1',
    registrationType: 'visitor',
    fullName: 'Anand Sundaram',
    email: 'anand.sundaram@investcoimbatore.in',
    phone: '+91 98430 11223',
    companyName: 'Kongu Retail Group',
    designation: 'Managing Partner',
    attendeesCount: 2,
    totalPrice: 0,
    status: 'confirmed',
    referenceCode: 'MCU-782190',
    notes: 'Interested in master franchise opportunities in FMCG sector.',
    createdAt: '2026-08-19T14:30:00Z',
  },
  {
    id: 'reg-102',
    eventId: 'evt-1',
    eventTitle: 'Tamil Nadu Franchise & Business Expo 2026',
    ticketTypeId: 't-2',
    registrationType: 'exhibitor',
    fullName: 'Priya Rajendran',
    email: 'priya.r@chennaibakes.com',
    phone: '+91 97909 88776',
    companyName: 'Madras Bakery Chains',
    designation: 'Head of Business Expansion',
    attendeesCount: 4,
    totalPrice: 15000,
    status: 'confirmed',
    referenceCode: 'MCU-445912',
    notes: 'Require 3x3 Octanorm booth space near food court pavilion.',
    createdAt: '2026-08-18T10:15:00Z',
  },
  {
    id: 'reg-103',
    eventId: 'evt-2',
    eventTitle: 'South India Digital Marketing Conclave 2026',
    ticketTypeId: 't-3',
    registrationType: 'visitor',
    fullName: 'Karthik Narayanan',
    email: 'karthik.n@growthfunnel.agency',
    phone: '+91 94441 55667',
    companyName: 'GrowthFunnel Digital',
    designation: 'Chief Marketing Officer',
    attendeesCount: 1,
    totalPrice: 2499,
    status: 'confirmed',
    referenceCode: 'MCU-993021',
    notes: 'Attending AI & Performance Ads Masterclass.',
    createdAt: '2026-08-17T16:45:00Z',
  },
  {
    id: 'reg-104',
    eventId: 'evt-1',
    eventTitle: 'Tamil Nadu Franchise & Business Expo 2026',
    ticketTypeId: 't-1',
    registrationType: 'visitor',
    fullName: 'Siddharth Varma',
    email: 'siddharth@varmaenterprises.com',
    phone: '+91 98840 99881',
    companyName: 'Varma Logistics & Warehousing',
    designation: 'Director',
    attendeesCount: 3,
    totalPrice: 0,
    status: 'pending',
    referenceCode: 'MCU-109283',
    notes: 'Looking for electric vehicle dealership franchises.',
    createdAt: '2026-08-16T11:20:00Z',
  },
  {
    id: 'reg-105',
    eventId: 'evt-3',
    eventTitle: 'Global Textile & Apparel Tech Expo 2026',
    ticketTypeId: 't-4',
    registrationType: 'visitor',
    fullName: 'Murugesan K.',
    email: 'murugesan@tirupurknits.org',
    phone: '+91 94433 22110',
    companyName: 'Tirupur Exporters Alliance',
    designation: 'Senior Vice President',
    attendeesCount: 5,
    totalPrice: 0,
    status: 'confirmed',
    referenceCode: 'MCU-623847',
    notes: 'Exploring sustainable dyeing and automated weaving machinery.',
    createdAt: '2026-08-15T09:00:00Z',
  },
];

export const mockEnquiries: Enquiry[] = [
  {
    id: 'enq-201',
    type: 'exhibitor',
    fullName: 'Ganesh Ramamurthy',
    email: 'ganesh.ram@texmach.in',
    phone: '+91 98422 77889',
    companyName: 'TexMach Automation Pvt Ltd',
    designation: 'Managing Director',
    subject: 'Stall Booking for Textile Tech Expo 2026',
    message: 'We want to reserve a 36 sq.m Bare Island Stall in Hall B for heavy circular knitting machinery demo.',
    eventId: 'evt-3',
    eventName: 'Global Textile & Apparel Tech Expo 2026',
    status: 'new',
    metadata: { stallSize: '36 sqm', powerRequirement: '25 kW 3-phase' },
    createdAt: '2026-08-19T17:10:00Z',
  },
  {
    id: 'enq-202',
    type: 'sponsor',
    fullName: 'Lakshmi Narayan',
    email: 'lakshmi.n@finvestcapital.com',
    phone: '+91 99620 44332',
    companyName: 'FinVest Capital South',
    designation: 'Head of Corporate Alliances',
    subject: 'Gold Sponsorship Proposal — Franchise Expo 2026',
    message: 'We would like to explore Gold Associate Sponsorship with VIP lounge branding and delegate bag inserts.',
    eventId: 'evt-1',
    eventName: 'Tamil Nadu Franchise & Business Expo 2026',
    status: 'in_progress',
    metadata: { sponsorshipBudget: '₹5,00,000', deliverables: ['VIP Lounge', 'Bag Inserts'] },
    createdAt: '2026-08-18T14:25:00Z',
  },
  {
    id: 'enq-203',
    type: 'digital_marketing',
    fullName: 'Dinesh Kumar',
    email: 'dinesh@kovaijewels.com',
    phone: '+91 97890 12345',
    companyName: 'Kovai Heritage Jewellers',
    designation: 'Marketing Head',
    subject: 'Omnichannel Performance Marketing for Festive Season',
    message: 'Looking for full-funnel Meta and Google Ads management + viral influencer reels production across Coimbatore & Salem.',
    status: 'new',
    metadata: { monthlyAdSpend: '₹3,00,000', targetLocations: ['Coimbatore', 'Salem', 'Erode'] },
    createdAt: '2026-08-18T09:40:00Z',
  },
  {
    id: 'enq-204',
    type: 'partnership',
    fullName: 'Prof. R. Chandrasekar',
    email: 'r.chandrasekar@psgtech.edu',
    phone: '+91 94421 88990',
    companyName: 'PSG Institute of Management',
    designation: 'Director — Industry Collaborations',
    subject: 'Academic & Knowledge Partnership for AI Conclave',
    message: 'Proposing faculty panel participation and 50 student delegate sponsorships for the Digital Creators Conclave.',
    eventId: 'evt-4',
    eventName: 'Digital Creators & Social Media Conclave 2026',
    status: 'contacted',
    createdAt: '2026-08-17T15:00:00Z',
  },
  {
    id: 'enq-205',
    type: 'event',
    fullName: 'Meera Vijayakumar',
    email: 'meera.v@naturalsfranchise.in',
    phone: '+91 98401 22334',
    companyName: 'Naturals Salon Franchise Network',
    designation: 'Franchise Relations Manager',
    subject: 'Speaker Slot & Masterclass Request',
    message: 'Our founder would like to deliver a 30-minute keynote on "Scaling Salon Chains to Tier-2 Cities".',
    eventId: 'evt-1',
    eventName: 'Tamil Nadu Franchise & Business Expo 2026',
    status: 'resolved',
    createdAt: '2026-08-16T12:30:00Z',
  },
];

