import { createFileRoute } from '@tanstack/react-router'
import { FileText, Search } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Input } from '@/components/ui/input'
import { supabase, type ContactSubmission } from '@/lib/supabase'
import { toast } from 'sonner'

export const Route = createFileRoute('/app/enquiries')({ head: () => ({ meta: [{ title: 'Contact Enquiries | MCU Events' }] }), component: Enquiries })
function Enquiries() { const [rows, setRows] = useState<ContactSubmission[]>([]); const [query, setQuery] = useState(''); useEffect(() => { async function load() { if (!supabase) return; const { data, error } = await supabase.from('contact_submissions').select('*').order('created_at', { ascending: false }); if (error) toast.error(error.message); else setRows(data ?? []) }; void load() }, []); const filtered = rows.filter(row => `${row.full_name} ${row.company_name} ${row.email} ${row.subject}`.toLowerCase().includes(query.toLowerCase())); return <div className="space-y-6"><div><h1 className="text-2xl font-semibold text-primary">Contact enquiries</h1><p className="mt-1 text-sm text-muted-foreground">Messages from the MCU Events website.</p></div><div className="relative max-w-sm"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" placeholder="Search enquiries" value={query} onChange={e => setQuery(e.target.value)} /></div><div className="overflow-x-auto rounded-xl border border-border bg-card"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-border bg-muted/50 text-xs uppercase tracking-wider text-muted-foreground"><tr>{['Name', 'Company', 'Email', 'Subject', 'Message', 'Date'].map(h => <th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{filtered.length ? filtered.map(row => <tr key={row.id} className="border-b border-border last:border-0"><td className="px-4 py-4 font-medium text-primary">{row.full_name}</td><td className="px-4 py-4">{row.company_name}</td><td className="px-4 py-4">{row.email}</td><td className="max-w-44 px-4 py-4">{row.subject}</td><td className="max-w-64 px-4 py-4 text-muted-foreground">{row.message}</td><td className="px-4 py-4 text-muted-foreground">{new Date(row.created_at).toLocaleDateString()}</td></tr>) : <tr><td colSpan={6} className="px-4 py-16 text-center text-muted-foreground"><FileText className="mx-auto mb-3 size-8 text-accent" />No enquiries found.</td></tr>}</tbody></table></div></div> }
