import { createFileRoute, Link } from '@tanstack/react-router'
import { ArrowLeft, LockKeyhole, Mail, ShieldCheck } from 'lucide-react'
import { FormEvent, useState } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { supabase } from '@/lib/supabase'
import { toast } from 'sonner'

export const Route = createFileRoute('/admin')({ head: () => ({ meta: [{ title: 'Admin Login | MCU Events' }, { name: 'description', content: 'Secure MCU Events administration.' }] }), component: AdminPage })

function AdminPage() { const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [loading, setLoading] = useState(false); async function submit(e: FormEvent) { e.preventDefault(); if (!supabase) { toast.error('Supabase is not connected yet.'); return }; setLoading(true); const { error } = await supabase.auth.signInWithPassword({ email, password }); setLoading(false); if (error) toast.error(error.message); else toast.success('Signed in. Your dashboard is ready.') }
  return <div className="min-h-dvh bg-secondary/50"><header className="border-b border-border bg-primary text-primary-foreground"><nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><Link to="/" className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-accent text-accent-foreground"><span className="font-serif text-xl font-bold">M</span></span><span className="font-bold tracking-[0.12em]">MCU <span className="font-normal text-primary-foreground/70">EVENTS</span></span></Link><Link to="/" className="text-sm text-primary-foreground/70 hover:text-accent"><ArrowLeft className="mr-2 inline size-4" />Back to home</Link></nav></header><main className="mx-auto flex min-h-[calc(100dvh-81px)] max-w-md items-center px-5 py-16"><div className="w-full rounded-3xl border border-border bg-card p-8 shadow-lg sm:p-10"><div className="grid size-12 place-items-center rounded-2xl bg-primary text-primary-foreground"><LockKeyhole className="size-5" /></div><p className="mt-8 text-xs font-bold uppercase tracking-[0.24em] text-accent">Private access</p><h1 className="mt-3 font-serif text-4xl text-primary">Admin login</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">Sign in with your Supabase admin account to view event registrations and contact enquiries.</p><form onSubmit={submit} className="mt-8 grid gap-5"><div><Label htmlFor="admin-email">Email address</Label><Input id="admin-email" required type="email" className="mt-2 h-11" value={email} onChange={e => setEmail(e.target.value)} /></div><div><Label htmlFor="admin-password">Password</Label><Input id="admin-password" required type="password" className="mt-2 h-11" value={password} onChange={e => setPassword(e.target.value)} /></div><Button disabled={loading} className="h-11 rounded-full bg-primary text-primary-foreground">{loading ? 'Signing in...' : 'Sign in securely'}</Button></form><div className="mt-7 flex gap-2 border-t border-border pt-5 text-xs leading-5 text-muted-foreground"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-accent" />Access is protected by Supabase Authentication and row-level security.</div></div></main></div>
}
