/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppRegistrationsRouteImport } from './routes/app/registrations'
import { Route as AppEnquiriesRouteImport } from './routes/app/enquiries'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRegistrationsRoute = AppRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AppRoute,
} as any)
const AppEnquiriesRoute = AppEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/app/enquiries': typeof AppEnquiriesRoute
  '/app/registrations': typeof AppRegistrationsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/app/enquiries': typeof AppEnquiriesRoute
  '/app/registrations': typeof AppRegistrationsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/app/enquiries': typeof AppEnquiriesRoute
  '/app/registrations': typeof AppRegistrationsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/contact'
    | '/register'
    | '/services'
    | '/app/enquiries'
    | '/app/registrations'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contact'
    | '/register'
    | '/services'
    | '/app/enquiries'
    | '/app/registrations'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/contact'
    | '/register'
    | '/services'
    | '/app/enquiries'
    | '/app/registrations'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  RegisterRoute: typeof RegisterRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/registrations': {
      id: '/app/registrations'
      path: '/registrations'
      fullPath: '/app/registrations'
      preLoaderRoute: typeof AppRegistrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/enquiries': {
      id: '/app/enquiries'
      path: '/enquiries'
      fullPath: '/app/enquiries'
      preLoaderRoute: typeof AppEnquiriesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppEnquiriesRoute: typeof AppEnquiriesRoute
  AppRegistrationsRoute: typeof AppRegistrationsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEnquiriesRoute: AppEnquiriesRoute,
  AppRegistrationsRoute: AppRegistrationsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  RegisterRoute: RegisterRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
